# http://www.appveyor.com/docs/appveyor-yml

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "4.1"
    - nodejs_version: "4.2"
    - nodejs_version: "5"

matrix:
  fast_finish: true

branches:
  except:
    - /^v[0-9]/

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  # Always use latest npm.
  - npm install -g npm
  # Typical npm stuff.
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # We test multiple Windows shells because of Node.js stdout buffering issues:
  # https://github.com/joyent/node/issues/3584
  - ps: "if ( -not $env:APPVEYOR_REPO_TAG ) { npm run ci-build } else { npm run ci-build-stable }"
  - cmd: "if [%APPVEYOR_REPO_TAG%] == [] npm run ci-build else npm run ci-build-stable"

# Don't actually build any .NET.
build: off

# Talk to Slack.
notifications:
  - provider: Slack
    auth_token:
      secure: jpmRZ9H5UGhAGstWdj0WWiLoz+NyL6+QrGVyzEkRkKLnwxi1ULuqkxSQ63D3LGr3eL2GiHbvxg5lzdrdirt82g==
    channel: mozu-build-status
